### PR TITLE
Revert "Bump aiohttp from 3.9.5 to 3.10.0"

### PR DESCRIPTION
**Pull request by dcermak**
Reverts SUSE/BCI-dockerfile-generator#1478

This update breaks py-obs which causes the update-versions action to fail. This is a temporary workaround until this is fixed upstream

### CODE REVIEW

**Comment by dirkmueller** [comment]
Should we have a pin on `pyproject.toml` to avoid a next lock update to undo this?

**Comment by dcermak** [comment]
In theory we don't have to, it should be fixed via https://github.com/dcermak/py-obs/pull/155

**Comment by dirkmueller** [comment]
> In theory we don't have to, it should be fixed via [dcermak/py-obs#155](https://github.com/dcermak/py-obs/pull/155)

Ah, nice debugging. it would also not be necessary with #1482 because that serializes access rather than using massively parallel async io ;)

**Comment by dcermak** [comment]
Closing in favor of #1500

**Pull request closed without merging**
