### PR TITLE
🤖: Update build recipes for Basalt

### PR DESCRIPTION
**Pull request by dcermak**
This is an automated pull request to update from branch for-deploy-Basalt

### CODE REVIEW

**Review by PVlasin — DISMISSED** [review]
OK

**Comment by dcermak** [comment]
/vc user=dancermak packages=sle15-kernel-module-devel-image Add ALP-dummy-release to fix build failures

**Review by PVlasin — APPROVED** [review]
OK

**Comment by dcermak** [comment]
/vc user=dancermak packages=basalt-kernel-module-devel-image Add ALP-dummy-release to fix build failures

**Pull request merged**
