### PR TITLE
🤖: Update build recipes for SP6

### PR DESCRIPTION
**Pull request by dcermak**
This is an automated pull request to update from branch for-deploy-6

### CODE REVIEW

**Comment by dcermak** [comment]
/vc user=dancermak packages=php-apache8-image,php8-image,php-fpm8-image Extend README

**Comment by dcermak** [comment]
/vc user=avicenzi packages=postgres-15-image,postgres-16-image Extend README

**Review by PVlasin — APPROVED** [review]
OK

**Pull request merged**
