### PR TITLE
naming policy cleanups

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by dcermak** [comment]
Is it intentional that some containers are now called `$something container` and others are just `$something`?

**Comment by vmoutoussamy** [comment]
I fully agree on these changes! Makes things more simple, easier to read and without loosing any important information.

**Comment by Vogtinator** [comment]
This is a bit weird now:

`<label name="org.opencontainers.image.description" value="%OS_VERSION_NO_DASH% BusyBox container based on the openSUSE Tumbleweed Base Container Image."/>`

Apart from the `container based on the ... Container Image` part, the `%OS_VERSION_NO_DASH%` replacement failed, resulting in `--config.label=org.opensuse.bci.busybox.description= BusyBox container based on the openSUSE Tumbleweed Base Container Image.`

**Comment by dirkmueller** [comment]
> Is it intentional that some containers are now called `$something container` and others are just `$something`?

"base containers" are "$flavor container", language and applications containers are just "$something"

**Comment by dirkmueller** [comment]
> This is a bit weird now:
> 
> `<label name="org.opencontainers.image.description" value="%OS_VERSION_NO_DASH% BusyBox container based on the openSUSE Tumbleweed Base Container Image."/>`
> 
> Apart from the `container based on the ... Container Image` part, the `%OS_VERSION_NO_DASH%` replacement failed, resulting in `--config.label=org.opensuse.bci.busybox.description= BusyBox container based on the openSUSE Tumbleweed Base Container Image.`

yeah thats a problem

**Comment by Vogtinator** [comment]
> > This is a bit weird now:
> > `<label name="org.opencontainers.image.description" value="%OS_VERSION_NO_DASH% BusyBox container based on the openSUSE Tumbleweed Base Container Image."/>`
> > Apart from the `container based on the ... Container Image` part, the `%OS_VERSION_NO_DASH%` replacement failed, resulting in `--config.label=org.opensuse.bci.busybox.description= BusyBox container based on the openSUSE Tumbleweed Base Container Image.`
> 
> yeah thats a problem

The reason is that TW's `os-release` does not define a `VERSION`, so only `%OS_VERSION_ID%` is usable

**Comment by dirkmueller** [comment]
> The reason is that TW's `os-release` does not define a `VERSION`, so only `%OS_VERSION_ID%` is usable

latest PR state should fix that issue

**Comment by dcermak** [comment]
The init, mirco and minimal containers have quite terrible titles with this change (although they were pretty bad before already…).

**Comment by dirkmueller** [comment]
> The init, mirco and minimal containers have quite terrible titles with this change (although they were pretty bad before already…).

so the change is ""SLE BCI SLE 15 SP5 Init"" which I agree looks bad. would you be happy with ""SLE BCI 15 SP5 Init" ?  I guess I can fix that.

**Comment by dcermak** [comment]
A few of the language stack containers now have odd sounding names like:
```
LABEL org.opencontainers.image.title="SLE BCI OpenJDK 17 development"
```
Maybe just drop the `development`?

Otherwise this LGTM, thanks @dirkmueller!!

**Review by vmoutoussamy — APPROVED** [review]
It was looking good for me before but now even better! Thanks @dirkmueller

**Comment by dirkmueller** [comment]
lets take further enhancements as a new PR. thanks for all the reviews!

**Pull request merged**
