### PR TITLE
Add `org.opencontainers.image.source` label to the build source

### PR DESCRIPTION
**Pull request by dcermak**
This fixes https://github.com/SUSE/BCI-dockerfile-generator/issues/252

### CODE REVIEW

**Comment by Vogtinator** [comment]
The URL doesn't point to a static page but the latest version. It should point to the exact revision used to build the image.

**Comment by dcermak** [comment]
> The URL doesn't point to a static page but the latest version. It should point to the exact revision used to build the image.

That is quite literally impossible. We'd have to know the sha of a commit before committing the sources…

**Comment by Vogtinator** [comment]
> > The URL doesn't point to a static page but the latest version. It should point to the exact revision used to build the image.
> 
> That is quite literally impossible. We'd have to know the sha of a commit before committing the sources…

`%SOURCEURL%` can do it, it uses the OBS revision and links to that specific one on sources.suse.com resp. build.opensuse.org.

**Comment by dirkmueller** [comment]
Iirc there's a separate label for specifying the git revision

**Comment by Vogtinator** [comment]
> Iirc there's a separate label for specifying the git revision

Yes, but that's technically for the contained software not the image itself: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys

**Comment by Vogtinator** [comment]
Can you try swapping the order of `docker_label_helper` and `kiwi_metainfo_helper` in `_service`? The label helper might not handle multiple `=` properly

**Comment by Vogtinator** [comment]
> Can you try swapping the order of `docker_label_helper` and `kiwi_metainfo_helper` in `_service`? The label helper might not handle multiple `=` properly

Fixed with https://build.opensuse.org/package/rdiff/openSUSE:Tools/obs-service-docker_label_helper?linkrev=base&rev=11. I can submit this to SLE as well if there's a bugref I can use.

**Comment by dcermak** [comment]
It appears to work:
```ShellSession
❯ skopeo inspect -f "{{index .Labels \"org.opencontainers.image.source\" }}" \
    docker://registry.opensuse.org/home/defolos/bci/staging/sle-15-sp4/sle15-sp4-vxscx/containerfile/bci/bci-init:latest
https://build.opensuse.org/package/show/home:defolos:BCI:Staging:SLE-15-SP4:sle15-sp4-vxSCx/init-image?rev=3d24af385dac7ab2414aa9be1f68e069
```

@dirkmueller @Vogtinator wdyt?

**Comment by Vogtinator** [comment]
LGTM!

**Review by fcrozat — APPROVED** [review]

**Pull request merged**
