### PR TITLE
Update latest to rust1.61

### PR DESCRIPTION
**Pull request by Firstyear**

### CODE REVIEW

**Review by dcermak — CHANGES_REQUESTED** [review]
Please format the source code to make the CI pass.

**Comment by Firstyear** [comment]
How do I format it?

**Comment by dcermak** [comment]
> How do I format it?

poetry install && poetry run black .

**Comment by Firstyear** [comment]
> How do I format it?
> poetry install && poetry run black .

Different question then. How can I format this in a sandbox / virtualenv or similar sinc I don't want to install poetry on my system (I've had so many bad experiences with trashing system python).

**Comment by dcermak** [comment]
> > How do I format it?
> > poetry install && poetry run black .
> 
> Different question then. How can I format this in a sandbox / virtualenv or similar sinc I don't want to install poetry on my system (I've had so many bad experiences with trashing system python).
> 
> EDIT: Found how to install black with out trashing my system.

`pip install --update --user poetry`? Or `podman run --name bci_poetry -it -v $(pwd):/src/:Z docker.io/fnndsc/python-poetry bash`

**Review by dcermak — APPROVED** [review]

**Pull request merged**
