### PR TITLE
Switch lifecycle url to the SLE15 specific url

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Review by dcermak — COMMENTED** [review]
We do not set the equivalent of `com.suse.lifecycle-url` for opensuse, so I am a bit hesitant to add another unused property to `ImageProperties`

**Comment by dirkmueller** [comment]
We could set it for opensuse as well in a follow-up PR

**Comment by dcermak** [comment]
> We could set it for opensuse as well in a follow-up PR

I have done that.

**Review by vmoutoussamy — COMMENTED** [review]
LGTM!

**Pull request merged**
