### PR TITLE
Use sentence-style capitalization

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
The `pretty_name` variable is used in the READMEs, we need to also change the README, otherwise, it will look like "Some package Container Image" and still be inconsistent.

**Review by alexandrevicenzi — COMMENTED** [review]
The pretty_name variable is used in the READMEs, we need to also change the README, otherwise, it will look like "Some package Container Image" and still be inconsistent.

**Comment by dirkmueller** [comment]
> The pretty_name variable is used in the READMEs, we need to also change the README, otherwise, it will look like "Some package Container Image" and still be inconsistent.

good catch. better now?

**Review by alexandrevicenzi — APPROVED** [review]

**Review by dcermak — APPROVED** [review]

**Comment by dirkmueller** [comment]
(checked with documentation team outside the PR, they're approving the change)

**Pull request merged**
