### PR TITLE
Add ALERTMANAGER_CONTAINERS

### PR DESCRIPTION
**Pull request by witekest**
Add automation to build Alertmanager container images.

### CODE REVIEW

**Comment by dcermak** [comment]
LGTM, have you build the container somewhere on OBS already?

**Comment by witekest** [comment]
No, I started with this one.

**Comment by witekest** [comment]
> LGTM, have you build the container somewhere on OBS already?

Here is the container at OBS
https://build.opensuse.org/package/show/home:witekbedyk:branches:devel:BCI:SLE-15-SP4/alertmanager-image

**Comment by dcermak** [comment]
Thanks!

**Pull request merged**
