### PR TITLE
🤖: Update build recipes for Tumbleweed

### PR DESCRIPTION
**Pull request by dcermak**
This is an automated pull request to update from branch for-deploy-Tumbleweed

### CODE REVIEW

**Comment by brunoleon** [comment]
/vc user=brunoleon Add an entrypoint for configuring and templating streams -  https://github.com/nginxinc/docker-nginx/pull/782

**Comment by brunoleon** [comment]
/vc user=brunoleon Add an entrypoint for configuring and templating streams -  https://github.com/nginxinc/docker-nginx/pull/782

**Comment by brunoleon** [comment]
/vc user=brunoleon Add an entrypoint for configuring and templating streams -  https://github.com/nginxinc/docker-nginx/pull/782

**Comment by brunoleon** [comment]
/vc user=brunoleon Add an entrypoint for configuring and templating streams -  https://github.com/nginxinc/docker-nginx/pull/782

**Review by dirkmueller — APPROVED** [review]

**Pull request merged**
