### PR TITLE
Add nss_synth for 389-ds to allow running as non-root

### PR DESCRIPTION
**Pull request by dcermak**
still pending submission to 15 SP4

### CODE REVIEW

**Review by Firstyear — APPROVED** [review]

**Comment by dcermak** [comment]
@Firstyear Are the required packages for this now in SLE 15 SP4? I.e. have they been released?

**Comment by Firstyear** [comment]
I really don't know how to check. I can see it in IBS, but I can't search/find it in an installed 15-SP4?

**Comment by Firstyear** [comment]
I think they've been released now? Can we check?

**Comment by dcermak** [comment]
> I think they've been released now? Can we check?

The package is not yet in the bci repo:

```ShellSession
🕙[ 08:39:48 ] ❯ podman run --rm -it registry.suse.com/bci/bci-base:15.4 zypper -n in nss_synth
Refreshing service 'container-suseconnect-zypp'.
Problem retrieving the repository index file for service 'container-suseconnect-zypp':
[container-suseconnect-zypp|file:/usr/lib/zypp/plugins/services/container-suseconnect-zypp] 
Warning: Skipping service 'container-suseconnect-zypp' because of the above error.
Retrieving repository 'SLE_BCI' metadata [done]
Building repository 'SLE_BCI' cache [done]
Loading repository data...
Reading installed packages...
'nss_synth' not found in package names. Trying capabilities.
No provider of 'nss_synth' found.
```

Please talk to maintenance where the release got stuck.

**Comment by Firstyear** [comment]
*screams internally*. Okay I'll ask.

**Pull request merged**
