### PR TITLE
Add 1.64

### PR DESCRIPTION
**Pull request by Firstyear**
Adds rust 1.64

### CODE REVIEW

**Comment by dcermak** [comment]
The package has not been released yet:
```ShellSession
$ podman run --rm -it registry.suse.com/bci/bci-base:15.4 zypper info rust1.64
Refreshing service 'container-suseconnect-zypp'.
Problem retrieving the repository index file for service 'container-suseconnect-zypp':
[container-suseconnect-zypp|file:/usr/lib/zypp/plugins/services/container-suseconnect-zypp] 
Warning: Skipping service 'container-suseconnect-zypp' because of the above error.
Retrieving repository 'SLE_BCI' metadata ..............................[done]
Building repository 'SLE_BCI' cache ...................................[done]
Loading repository data...
Reading installed packages...


package 'rust1.64' not found.
```

**Comment by Firstyear** [comment]
Yeah I normally add the pr for the version when I do the SR/MR, because I don't understand how to get visibility into the process of "when it's released".

**Comment by dcermak** [comment]
> Yeah I normally add the pr for the version when I do the SR/MR, because I don't understand how to get visibility into the process of "when it's released".

Whenever a maintenance request is created, maintenance will give you a link to smelt, which will give you the dates.

**Comment by Firstyear** [comment]
> > Yeah I normally add the pr for the version when I do the SR/MR, because I don't understand how to get visibility into the process of "when it's released".
> 
> Whenever a maintenance request is created, maintenance will give you a link to smelt, which will give you the dates.

I have never once seen this. o_o

**Comment by dirkmueller** [comment]
Looks like this is https://maintenance.suse.de/request/281940/

**Comment by Firstyear** [comment]
Does that mean we can merge this then?

**Pull request merged**
