### PR TITLE
🤖: Update build recipes for SP6

### PR DESCRIPTION
**Pull request by dcermak**
This is an automated pull request to update from branch for-deploy-6

### CODE REVIEW

**Comment by dcermak** [comment]
/vc user=avicenzi packages=nginx-image,rmt-nginx-image Extend README.md

**Comment by dcermak** [comment]
/vc user=dancermak packages=rmt-mariadb-image Bump mariadb version in docker-entrypoint.sh

**Review by dirkmueller — APPROVED** [review]

**Pull request merged**
