### PR TITLE
🤖: Update build recipes for SP5

### PR DESCRIPTION
**Pull request by dcermak**
This is an automated pull request to update from branch for-deploy-5

### CODE REVIEW

**Comment by dcermak** [comment]
/vc user=dirkmueller packages=nodejs-18-image Align end of support date with SLE 15 SP5

**Review by dirkmueller — DISMISSED** [review]
waiting for confirmation from Maintenance PM

**Comment by dcermak** [comment]
/vc user=dirkmueller update README; reduce unnecessary newlines

**Comment by dirkmueller** [comment]
/vc user=dirkmueller packages=init-image,minimal-image,micro-image Add end of support date aligned with SLE 15 SP5

**Review by dirkmueller — APPROVED** [review]

**Pull request merged**
