### PR TITLE
Set oci base image reference and digest annotations

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Review by alexandrevicenzi — APPROVED** [review]

**Comment by dcermak** [comment]
This doesn't work on Tumbleweed:
```
❯ skopeo inspect docker://registry.opensuse.org/home/defolos/bci/staging/tumbleweed/tumbleweed-1509/containerfile/opensuse/bci/bci-init
{
# snip
    "Labels": {
        "org.opencontainers.image.base.digest": "%BASE_TUMBLEWEED_DIGEST%",
        "org.opencontainers.image.base.name": "%BASE_TUMBLEWEED_REFERENCE%",
```

**Review by dcermak — CHANGES_REQUESTED** [review]
This also doesn't work in SLES:
```
❯ skopeo inspect -f '{{index .Labels "org.opencontainers.image.base.digest" }}' docker://registry.opensuse.org/home/defolos/bci/staging/sle-15-sp6/6-1509/images/suse/helm:3.13
%BASE_BCI_MICRO_DIGEST%

```

**Comment by dirkmueller** [comment]
it needs changes in the metainfo_label_helper

**Comment by dirkmueller** [comment]
we'll implement it directly in the build service, which seems easier than getting it into BCI

**Pull request closed without merging**
